const KEYS = Object.freeze({
  QUERY: {
    WORKS: 'WORKS',
    WORK_SEARCHES: 'WORK_SEARCHES'
  },
  MUTATION: {
    CREATE_WORK: 'CREATE_WORK',
    DELETE_WORK: 'DELETE_WORK',
    EDIT_WORK: 'EDIT_WORK',
    DELETE_PERMANENT_WORK: 'DELETE_PERMANENT_WORK',
    SEARCH_WORK: 'SEARCH_WORK',
    CREATE_WORK_SEARCH: 'CREATE_WORK_SEARCH',
    EDIT_WORK_SEARCH: 'EDIT_WORK_SEARCH',
    DELETE_PERMANENT_WORK_SEARCH: 'DELETE_PERMANENT_WORK_SEARCH'
  }
})

export default KEYS
